# Generated by Django 6.1 on 2026-08-10 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FundHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('number_of_schemes', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NAVSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('PARTIAL', 'Partial'), ('FAILED', 'Failed')], max_length=20)),
                ('records_received', models.PositiveIntegerField(default=0)),
                ('records_created', models.PositiveIntegerField(default=0)),
                ('new_schemes', models.PositiveIntegerField(default=0)),
                ('deactivated_schemes', models.PositiveIntegerField(default=0)),
                ('duplicate_records', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('source_url', models.URLField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MutualFundScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme_code', models.CharField(max_length=50, unique=True)),
                ('scheme_name', models.CharField(max_length=500)),
                ('isin_div_payout', models.CharField(blank=True, max_length=50, null=True)),
                ('isin_div_reinvestment', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('first_seen_date', models.DateField(blank=True, null=True)),
                ('last_seen_date', models.DateField(blank=True, null=True)),
                ('deactivated_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fund_house', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schemes', to='mutual_funds.fundhouse')),
            ],
        ),
        migrations.CreateModel(
            name='MutualFundNAV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nav', models.DecimalField(decimal_places=4, max_digits=20)),
                ('repurchase_price', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('nav_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nav_history', to='mutual_funds.mutualfundscheme')),
            ],
            options={
                'ordering': ['-nav_date'],
                'constraints': [models.UniqueConstraint(fields=('scheme', 'nav_date'), name='unique_scheme_nav_date')],
            },
        ),
    ]
