# Generated by Django 6.1 on 2026-08-17 11:08

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mutual_funds', '0006_rename_nav_history_mutualfundscheme_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My Portfolio', max_length=255)),
                ('risk_profile', models.CharField(blank=True, choices=[('CONSERVATIVE', 'Conservative'), ('MODERATE', 'Moderate'), ('AGGRESSIVE', 'Aggressive')], max_length=20, null=True)),
                ('target_equity_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('target_debt_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='PortfolioImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('CAS', 'CAS'), ('API', 'API'), ('MANUAL', 'Manual')], default='CAS', max_length=20)),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('PROCESSING', 'Processing'), ('SUCCESS', 'Success'), ('PARTIAL', 'Partial'), ('FAILED', 'Failed')], default='UPLOADED', max_length=20)),
                ('file_name', models.CharField(blank=True, max_length=500, null=True)),
                ('records_found', models.PositiveIntegerField(default=0)),
                ('records_created', models.PositiveIntegerField(default=0)),
                ('records_updated', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imports', to='portfolio_analysis.portfolio')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PortfolioHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio_number', models.CharField(blank=True, max_length=255, null=True)),
                ('units', models.DecimalField(decimal_places=6, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))])),
                ('invested_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('current_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('current_nav', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('current_nav_date', models.DateField(blank=True, null=True)),
                ('source', models.CharField(default='CAS', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='portfolio_analysis.portfolio')),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='portfolio_holdings', to='mutual_funds.mutualfundscheme')),
            ],
            options={
                'ordering': ('scheme__scheme_name',),
                'constraints': [models.UniqueConstraint(fields=('portfolio', 'scheme', 'folio_number'), name='unique_portfolio_scheme_folio')],
            },
        ),
        migrations.CreateModel(
            name='PortfolioSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField()),
                ('total_invested_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('total_current_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('total_gain', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('total_gain_percentage', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10)),
                ('equity_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('debt_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='portfolio_analysis.portfolio')),
            ],
            options={
                'ordering': ('-snapshot_date',),
                'constraints': [models.UniqueConstraint(fields=('portfolio', 'snapshot_date'), name='unique_portfolio_snapshot_date')],
            },
        ),
    ]
