# Generated by Django 6.1 on 2026-08-18 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_analysis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='portfolioholding',
            name='unique_portfolio_scheme_folio',
        ),
        migrations.RemoveConstraint(
            model_name='portfoliosnapshot',
            name='unique_portfolio_snapshot_date',
        ),
        migrations.AlterModelOptions(
            name='portfolio',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='portfolioimport',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='name',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='risk_profile',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='target_debt_percentage',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='target_equity_percentage',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='user',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='mutual_fund_details',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='pan',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='portfolio_totals',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RemoveField(
            model_name='portfoliosnapshot',
            name='portfolio',
        ),
        migrations.DeleteModel(
            name='PortfolioHolding',
        ),
        migrations.DeleteModel(
            name='PortfolioSnapshot',
        ),
    ]
