# Generated by Django 6.1 on 2026-08-11 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mutual_funds', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mutualfundscheme',
            options={'ordering': ['fund_house__name', 'scheme_name']},
        ),
        migrations.RemoveField(
            model_name='fundhouse',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='fundhouse',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='mutualfundnav',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='mutualfundscheme',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='mutualfundscheme',
            name='updated_at',
        ),
        migrations.AddIndex(
            model_name='mutualfundnav',
            index=models.Index(fields=['scheme', '-nav_date'], name='nav_scheme_date_idx'),
        ),
        migrations.AddIndex(
            model_name='mutualfundnav',
            index=models.Index(fields=['nav_date'], name='nav_date_idx'),
        ),
    ]
