# Generated by Django 6.1 on 2026-08-11 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mutual_funds', '0003_remove_mutualfundnav_nav_scheme_date_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mutualfundscheme',
            name='deactivated_date',
        ),
        migrations.RemoveField(
            model_name='mutualfundscheme',
            name='first_seen_date',
        ),
        migrations.RemoveField(
            model_name='mutualfundscheme',
            name='isin_div_payout',
        ),
        migrations.RemoveField(
            model_name='mutualfundscheme',
            name='last_seen_date',
        ),
        migrations.AlterField(
            model_name='mutualfundscheme',
            name='isin_div_reinvestment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mutualfundscheme',
            name='isin_growth',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mutualfundscheme',
            name='scheme_category',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
