# Generated by Django 6.1 on 2026-08-11 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mutual_funds', '0002_alter_mutualfundscheme_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='mutualfundnav',
            name='nav_scheme_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='mutualfundnav',
            name='nav_date_idx',
        ),
        migrations.RemoveConstraint(
            model_name='mutualfundnav',
            name='unique_scheme_nav_date',
        ),
        migrations.AlterModelOptions(
            name='mutualfundscheme',
            options={},
        ),
        migrations.AddField(
            model_name='mutualfundscheme',
            name='isin_growth',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mutualfundscheme',
            name='nav_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='mutualfundscheme',
            name='scheme_category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mutualfundscheme',
            name='scheme_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='MutualFundNAV',
        ),
    ]
