# Generated by Django 6.1 on 2026-08-11 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mutual_funds', '0004_remove_mutualfundscheme_deactivated_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mutualfundscheme',
            name='isin_div_payout',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mutualfundscheme',
            name='scheme_category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
