# Generated by Django 6.1 on 2026-08-13 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mutual_funds', '0005_mutualfundscheme_isin_div_payout_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mutualfundscheme',
            old_name='nav_history',
            new_name='data',
        ),
    ]
